[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rag-evaluation-framework"
version = "0.1.0"
description = "RAG Evaluation Framework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
